name: Our Workflow
on: push
jobs:
  calculate:
    runs-on: [self-hosted, Linux]
    steps:
      - id: calc
        uses: andrew-ch-lee/test-action@main
        with:
          x: 12
          y: 3
      - name: Print results
        run: |
          echo "x + y = ${{ steps.calc.outputs.plus }}"
          echo "x - y = ${{ steps.calc.outputs.minus }}"
